### ISSUE TITLE
Instructions where unclear, got laptop stuck in ceiling fan

### ISSUE THREAD

**Issue by kennethlynne** [localytics/serverless-slackbot-scaffold#15]
Just wondering what kind of integration one should use :+1: 

![image](https://cloud.githubusercontent.com/assets/390817/13952578/6bdf8ba6-f037-11e5-9fc8-3f79d7cc9ad5.png)

**Comment by kennethlynne** [comment]
Should probably be added to the readme for noobs like me :dancer:

**Comment by kddeisz** [comment]
Hey @kennethlynne, you want "slash commands."

**Comment by kddeisz** [comment]
I'll add it to the README, thanks.

**Comment by kennethlynne** [comment]
Well thanks, less than 30 sec response time!

**Comment by kddeisz** [comment]
We try!

**Comment by kddeisz** [comment]
Pushed
