### ISSUE TITLE
Add a link to s3 bucket name conventions

### ISSUE THREAD

**Issue by kennethlynne** [localytics/serverless-slackbot-scaffold#17]
Would be nice if this quote had a clickable link, so that lazy noobs can read up on the conventions and save them selves from derping.

"This will need to follow the Serverless convention of having the region in the name, and will typically look something like serverless.us-east-1.localytics."

**Comment by kddeisz** [comment]
Yeah, unfortunately it doesn't really appear to be documented. The corresponding code is here: https://github.com/serverless/serverless/blob/master/lib/utils/aws/S3.js#L31 but I'm hesitant to put a link to source in the README.

**Comment by kennethlynne** [comment]
Ok, thanks!
