### ISSUE TITLE
No postback url received

### ISSUE THREAD

**Issue by kennethlynne** [localytics/serverless-slackbot-scaffold#19]
```
    $ sls resources deploy -s <stage>

Next, deploy the function and endpoint:

    $ cd nodejs
    $ sls dash deploy -s <stage>

Take the postback url, enter it into the slack integration configuration, and save.
```

Output:
```
 nodejs sls resources deploy -s prod
Serverless: Deploying resources to stage "prod" in region "us-east-1" via Cloudformation (~3 minutes)...  
Serverless: Successfully deployed "prod" resources to "us-east-1"  
➜  nodejs 
```

Also the created cloudformation stack only creates some roles, but should probably scaffold some lambdas and/or API gateways?
![image](https://cloud.githubusercontent.com/assets/390817/13953962/f0aede5c-f03e-11e5-9f7b-613ccbb83daa.png)

**Comment by kddeisz** [comment]
You only deployed the CF resources. You need to actually deploy the endpoints and lambdas to get the postback URL.

**Comment by kddeisz** [comment]
I just tested again, and on my machine it returns a postback. Let me know if you can't get it working once you deploy the lambda.
