### ISSUE TITLE
Missing dev region json file - sls resources deploy fails due to inability to select region

### ISSUE THREAD

**Issue by stormlrd** [localytics/serverless-slackbot-scaffold#27]
Hi,

Have run this a couple of times now and the default project directory is missing a json file in the _meta/variables sub directory.

I created one for tokoyo calling it s-variables-dev-apnortheast1.json  and put 
{
  "region": "ap-northeast-1"
}   

into it, and then the sls resources deploy started working for me.

Otherwise it would prompt me to select a region, and there wasn't anything to choose from. It would bomb out.

**Comment by kddeisz** [comment]
Yeah I was thinking about that. Didn't want to enforce a region but maybe it's worth it so that it doesn't break when it first starts.

**Comment by stormlrd** [comment]
Yeah sorry. I came at this as a complete noob to both Khaos, Serverless so this one made me spend a few moments scratching the documents and having a sniff :)   Fortunately it taught me somethings I probably wouldn't have learnt if it just worked outright lol :)

**Comment by kddeisz** [comment]
So I was just looking at this more - it looks like Khaos provides a way to do the generation programmatically, but that would mean people would have to download the repo, which bypasses the whole reason we went with Khaos. I think the solution is either we build in a default region and have people change it when they build it or just put a section in the README explaining what needs to be done after it's been run. What do you think?

**Comment by stormlrd** [comment]
Put it in the readme :)

On Mon, May 30, 2016 at 4:43 AM, Kevin Deisz <notifications@github.com>
wrote:

> So I was just looking at this more - it looks like Khaos provides a way to
> do the generation programmatically, but that would mean people would have
> to download the repo, which bypasses the whole reason we went with Khaos. I
> think the solution is either we build in a default region and have people
> change it when they build it or just put a section in the README explaining
> what needs to be done after it's been run. What do you think?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/localytics/serverless-slackbot-scaffold/issues/27#issuecomment-222370144>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMpb4lSvTZDDBHO9o8lpEEXD_Qx0hIhtks5qGcIvgaJpZM4IpDkP>
> .
>



-- 
Paul

**Comment by kddeisz** [comment]
So I just realized it's actually in the README, but I had accidentally gitignored the region file so it didn't get pushed to the template. I've got it all fixed now so people just need to run `sls init` if they want things other than the default.
